### ISSUE TITLE
程序出现以下异常

### ISSUE THREAD

**Issue by loloazz** [hwkxk/HeytapTask#19]
```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\Anaconda3\envs\pythonShell\lib\site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\Anaconda3\envs\pythonShell\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda3\envs\pythonShell\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname
python-BaseException

```

**Comment by hwkxk** [comment]
#### 检查是否设置了代理/VPN，如果有，请关闭！
项目的 使用注意 已经写明了！
> 部分域名屏蔽境外IP访问，所以本项目不适于在 非中国IP代理网络下 / Github Actions / 境外VPS 上运行!

**Comment by loloazz** [comment]
已解决！
