### ISSUE TITLE
【每日浏览任务】: 错误，原因为: 'detail'

### ISSUE THREAD

**Issue by nssiwi** [hwkxk/HeytapTask#27]
```
Traceback (most recent call last):

  File "/var/user/main.py", line 164, in daily_viewgoods

    for skuinfo in res['detail']:

KeyError: 'detail'

【每日浏览任务】: 错误，原因为: 'detail'

[2021-08-07 00:00:05,181]:ERROR:【每日浏览任务】: 错误，原因为: 'detail'
```

**Comment by yinmai0506** [comment]
Traceback (most recent call last):

  File "/var/user/index.py", line 164, in daily_viewgoods

    for skuinfo in res['detail']:

KeyError: 'detail'


【每日浏览任务】: 错误，原因为: 'detail'

**Comment by spiritLHL** [comment]
+1

**Comment by yinmai0506** [comment]
+1

**Comment by hwkxk** [comment]
知道的了，晚点再修…

**Comment by hwkxk** [comment]
#### 2021.8.7 11:10  已修复（商品列表接口更改，已重新抓取）
