### ISSUE TITLE
我的一直提示字符解码报错

### ISSUE THREAD

**Issue by asqw9527** [hwkxk/HeytapTask#3]
UnicodeEncodeError: 'latin-1' codec can't encode character '\uff1b' in position 47: ordinal not in range(256)

**Comment by asqw9527** [comment]
请问这个要怎么处理？

**Comment by hwkxk** [comment]
### 请一定要使用UTF-8编码保存配置文件！

[![WYvO74.jpg](https://z3.ax1x.com/2021/07/20/WYvO74.jpg)](https://imgtu.com/i/WYvO74)

**Comment by asqw9527** [comment]
我的已经是utf-8了

**Comment by asqw9527** [comment]
Traceback (most recent call last):
  File "main.py", line 32, in readConfig
    userconfig.read(path,encoding="utf-8")
  File "C:\Program Files\python\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "C:\Program Files\python\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: './config.ini', line: 1
'\ufeff# 定义config分组 必需项！\n'

[2021-07-20 11:40:17,506]:ERROR:1.请检查是否在目录下建立了config.ini
Traceback (most recent call last):
  File "main.py", line 332, in <module>
    main("","")
  File "main.py", line 305, in main
    HT_cookies = users.get("config","cookies")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by asqw9527** [comment]
我刚才设置成带bom的utf-8，可以了，但是又报这个错误

**Comment by hwkxk** [comment]
> 我的已经是utf-8了

\uff1b 检查一下 有没有在中文模式输入的标点符号，必须分号\引号都是英文的

**Comment by asqw9527** [comment]
刚才看了下config和User-Agent中的分号都是英文

**Comment by hwkxk** [comment]
> 刚才看了下config和User-Agent中的分号都是英文

我测试我的台式和笔记本都没出现这个问题。
[![WtPoa8.jpg](https://z3.ax1x.com/2021/07/20/WtPoa8.jpg)](https://imgtu.com/i/WtPoa8)
打开main.py 第33行 
`userconfig.read(path,encoding="utf-8")`
改成：
`userconfig.read(path,encoding="utf-8-sig")`
试试

**Comment by asqw9527** [comment]
> > 刚才的分析下配置和User-Agent中的分号都是英文
> 
> 我测试我的台式和笔记本都没出现这个问题。 打开main.py第33行 改成： 试试
> [![WtPoa8.jpg](https://camo.githubusercontent.com/f249f2cc9b88e7d59978cd39e2c56c311a9c74544106b2d7974793226c921927/68747470733a2f2f7a332e617831782e636f6d2f323032312f30372f32302f5774506f61382e6a7067)](https://imgtu.com/i/WtPoa8)
> 
> `userconfig.read(path,encoding="utf-8")`
> 
> `userconfig.read(path,encoding="utf-8-sig")`

加上这两行代码还是这个错误，如果方便的话，可以远程帮我看下吗？扣扣：1906356418，我加上cookies就会报错，我看了下，没有中文符号，

**Comment by hwkxk** [comment]
那不知道什么问题了，我已经把我的配置文件贴图了，按照说明来填并且编码是uft-8，应该都不会有什么问题，并且我自己已经在2台电脑且云函数上测试通过。自己再仔细检查一下吧，在工作不方便，不加QQ。

**Comment by asqw9527** [comment]
可以了，谢谢，我刚重新复制了下，就可以了
多谢多谢，我看没有抽奖的
