### ISSUE TITLE
 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by rubnet** [hwkxk/HeytapTask#44]
INFO:【每日签到成功】: 积分+5,签到礼:耳 机优惠券
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/HeytapTask-main/main.py", line 157, in daily_viewgoods
    for data in res:
TypeError: 'NoneType' object is not iterable

[2021-09-12 ]:ERROR:【每日浏览任务】: 错误，原因为: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/HeytapTask-main/main.py", line 204, in daily_sharegoods
    for data in res:
TypeError: 'NoneType' object is not iterable

[2021-09-12]:ERROR:【每日分享商品】: 错误，原因为: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/downloads/HeytapTask-main/main.py", line 245, in daily_viewpush
    for data in res:
TypeError: 'NoneType' object is not iterable

[2021-09-12 ]:ERROR:【每日推送消息】: 错误，原因为: 'NoneType' object is not iterable

**Comment by rubnet** [comment]
没有配置  推送消息 首次就会报错，重新运行就不会了

**Comment by hwkxk** [comment]
要么是新号自己没有去APP任务中心激活，要么是网络问题返回的任务数据不全之类的。不配置推送不会出现这样的错误。

**Comment by rubnet** [comment]
应该是没有去APP任务中心激活
