### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by miaoxiaozhao** [hwkxk/HeytapTask#5]
`Traceback (most recent call last):
  File "/web/HeytapTask/main.py", line 332, in <module>
    main("","")
  File "/web/HeytapTask/main.py", line 305, in main
    HT_cookies = users.get("config","cookies")
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'config'`

我无论是直接复制，还是只填写sa_distinct_id=、TOKENSID=、ENCODE_TOKENSI=、app_param=、 这几项，都报错，不知道出错在哪里。

**Comment by hwkxk** [comment]
#### config.ini 文件路径不对，没有在运行目录下 或者 config.ini 里面的[config]被注释或删了？
正确格式如图：
[![Wa9a34.jpg](https://z3.ax1x.com/2021/07/21/Wa9a34.jpg)](https://imgtu.com/i/Wa9a34)
