### ISSUE TITLE
有大佬帮我解决下吗？

### ISSUE THREAD

**Issue by liu-wenyan** [hwkxk/HeytapTask#54]
我没有修改过main.py文件，就按着教程获取cookies运行后就出现这个问题了,有大佬帮忙解决下吗？谢谢！
`[2021-10-20 19:03:30,954]:ERROR:1.请检查是否在目录下建立了config.ini
Traceback (most recent call last):
  File "C:\Users\12995\Desktop\HeytapTask-main\main.py", line 333, in <module>
    main("","")
  File "C:\Users\12995\Desktop\HeytapTask-main\main.py", line 306, in main
    HT_cookies = users.get("config","cookies")
AttributeError: 'NoneType' object has no attribute 'get'
`

**Comment by liu-wenyan** [comment]
![image](https://user-images.githubusercontent.com/63504142/138083551-4096219b-917d-45b8-9281-3a890b4a7c8c.png)

**Comment by liu-wenyan** [comment]
![image](https://user-images.githubusercontent.com/63504142/138083571-4048c104-c1b8-4218-95cf-086241b0cd51.png)

**Comment by liu-wenyan** [comment]
这俩问题不是很能理解

**Comment by hwkxk** [comment]
我也不清楚，你的配置文件仔细看看是不是填错了，或尝试换python自带的IDLE运行试试
