### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by sum211** [hwkxk/HeytapTask#7]
Traceback (most recent call last):
  File "main.py", line 332, in <module>
    main("","")
  File "main.py", line 308, in main
    client = get_infouser(HT_cookies,HT_UserAgent)
  File "main.py", line 53, in get_infouser
    response = session.get('https://www.heytap.com/cn/oapi/users/web/member/info', headers=headers)
  File "D:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Program Files\Python37\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "D:\Program Files\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "D:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "D:\Program Files\Python37\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Program Files\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Program Files\Python37\lib\http\client.py", line 1270, in _send_request
    self.putheader(hdr, value)
  File "D:\Program Files\Python37\lib\http\client.py", line 1202, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 2350-2354: ordinal not in range(256)

这是为什么

**Comment by hwkxk** [comment]
#### 自己检查网络 www.heytap.com 国外IP无法访问的

**Comment by sum211** [comment]
我再查查
